set positional-arguments

alembic_revision := "-1"

# Show available recipes.
default:
    @just --list --unsorted

# Install runtime and development dependencies with uv.
[group('setup')]
install:
    uv sync --group dev

# Create .env from .env.example if it does not already exist.
[group('setup')]
env:
    @test -f .env || cp .env.example .env

# Generate a Fernet key for DEPLOYMENT_SECRET_KEY.
[group('setup')]
fernet-key:
    uv run python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"

# Start local Postgres and Redis containers.
[group('infra')]
infra:
    docker compose up -d postgres redis

# Follow local Postgres and Redis logs.
[group('infra')]
infra-logs:
    docker compose logs -f postgres redis

# Stop local infrastructure containers.
[group('infra')]
infra-down:
    docker compose down

# Stop infrastructure containers and remove their volumes.
[confirm("Remove infrastructure containers AND their volumes? All local data is lost. [y/N]")]
[group('infra')]
infra-clean:
    docker compose down -v

# Apply all database migrations.
[group('db')]
migrate:
    uv run --env-file .env alembic upgrade head

# Roll back database migrations. Usage: just migrate-down [revision]
[group('db')]
migrate-down revision=alembic_revision:
    uv run --env-file .env alembic downgrade {{ quote(revision) }}

# Show the current database migration revision.
[group('db')]
db-current:
    uv run --env-file .env alembic current

# Show database migration history.
[group('db')]
db-history:
    uv run --env-file .env alembic history --verbose

# Create an autogenerated migration. Usage: just revision 'describe change'
[group('db')]
revision msg:
    uv run --env-file .env alembic revision --autogenerate -m {{ quote(msg) }}

# Run all app processes from Procfile with overmind.
[group('run')]
dev:
    uv run overmind start

# Force-stop overmind managed dev processes.
[group('run')]
dev-stop:
    -uv run overmind kill
    -pkill -f "overmind-discode|discode-bot|discode-runner|discode-dispatcher|discode-janitor"

# Run the Discord bot process.
[group('run')]
bot:
    uv run discode-bot

# Run the runner process.
[group('run')]
runner:
    uv run discode-runner

# Run the dispatcher process.
[group('run')]
dispatcher:
    uv run discode-dispatcher

# Run the janitor process.
[group('run')]
janitor:
    uv run discode-janitor

# Format source and tests with ruff.
[group('quality')]
format:
    uv run ruff format src tests

# Lint source and tests.
[group('quality')]
lint:
    uv run ruff check src tests

# Apply safe ruff fixes.
[group('quality')]
lint-fix:
    uv run ruff check --fix src tests

# Run strict mypy checks for the package.
[group('quality')]
typecheck:
    uv run mypy src/discode --strict

# Run pytest. Usage: just test [tests/path -k expr]
[group('quality')]
test *args:
    uv run pytest "$@" || [ $? -eq 5 ]

# Run tests, stopping at the first failure. Usage: just test-fast [tests/path]
[group('quality')]
test-fast *args:
    uv run pytest -x "$@" || [ $? -eq 5 ]

# Scan for leaked secrets with gitleaks.
[group('quality')]
secrets-scan:
    gitleaks detect --source . --config .gitleaks.toml

# Run lint, typecheck, and tests.
[group('quality')]
check: lint typecheck test

# Audit locked dependencies against the OSV vulnerability database.
[group('quality')]
audit:
    uv export --format requirements-txt --no-emit-project | uvx pip-audit --disable-pip -r /dev/stdin

# Remove local Python/tool caches.
clean:
    rm -rf .mypy_cache .pytest_cache .ruff_cache
    find . -type d -name __pycache__ -prune -exec rm -rf {} +
