.DEFAULT_GOAL := help

PYTEST_ARGS ?=
ALEMBIC_REVISION ?= -1

.PHONY: help install env fernet-key infra infra-logs infra-down infra-clean migrate migrate-down db-current db-history revision dev dev-stop bot runner dispatcher janitor format lint lint-fix typecheck test test-fast check clean

help:
	@awk 'BEGIN {FS = ":.*##"; printf "Usage: make <target>\n\nTargets:\n"} /^[a-zA-Z0-9_-]+:.*##/ {printf "  %-18s %s\n", $$1, $$2}' $(MAKEFILE_LIST)

install: ## Install runtime and development dependencies with uv.
	uv sync --group dev

env: ## Create .env from .env.example if it does not already exist.
	@test -f .env || cp .env.example .env

fernet-key: ## Generate a Fernet key for DEPLOYMENT_SECRET_KEY.
	uv run python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"

infra: ## Start local Postgres and Redis containers.
	docker compose up -d postgres redis

infra-logs: ## Follow local Postgres and Redis logs.
	docker compose logs -f postgres redis

infra-down: ## Stop local infrastructure containers.
	docker compose down

infra-clean: ## Stop infrastructure containers and remove their volumes.
	docker compose down -v

migrate: ## Apply all database migrations.
	uv run --env-file .env alembic upgrade head

migrate-down: ## Roll back database migrations. Override with ALEMBIC_REVISION=<rev>.
	uv run --env-file .env alembic downgrade $(ALEMBIC_REVISION)

db-current: ## Show the current database migration revision.
	uv run --env-file .env alembic current

db-history: ## Show database migration history.
	uv run --env-file .env alembic history --verbose

revision: ## Create an autogenerated migration. Usage: make revision MSG='describe change'
	@test -n "$(MSG)" || (echo "Usage: make revision MSG='describe change'" && exit 2)
	MSG='$(subst ','\'',$(MSG))' && uv run --env-file .env alembic revision --autogenerate -m "$$MSG"

dev: ## Run all app processes from Procfile with overmind.
	uv run overmind start

dev-stop: ## Force-stop overmind managed dev processes.
	-uv run overmind kill
	-pkill -f "overmind-discode|discode-bot|discode-runner|discode-dispatcher|discode-janitor"

bot: ## Run the Discord bot process.
	uv run discode-bot

runner: ## Run the runner process.
	uv run discode-runner

dispatcher: ## Run the dispatcher process.
	uv run discode-dispatcher

janitor: ## Run the janitor process.
	uv run discode-janitor

format: ## Format source and tests with ruff.
	uv run ruff format src tests

lint: ## Lint source and tests.
	uv run ruff check src tests

lint-fix: ## Apply safe ruff fixes.
	uv run ruff check --fix src tests

typecheck: ## Run strict mypy checks for the package.
	uv run mypy src/discode --strict

test: ## Run pytest. Pass PYTEST_ARGS='tests/path -k expr' to filter.
	uv run pytest $(PYTEST_ARGS) || [ $$? -eq 5 ]

test-fast: ## Run tests, stopping at the first failure.
	uv run pytest -x $(PYTEST_ARGS) || [ $$? -eq 5 ]

secrets-scan: ## Scan for leaked secrets with gitleaks.
	gitleaks detect --source . --config .gitleaks.toml

check: ## Run lint, typecheck, and tests.
	$(MAKE) lint
	$(MAKE) typecheck
	$(MAKE) test

clean: ## Remove local Python/tool caches.
	rm -rf .mypy_cache .pytest_cache .ruff_cache
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
